### ISSUE TITLE
Possible to get full asset path name?

### ISSUE THREAD

**Issue by kvnxiao** [Razmoth/HoYoStudio#20]
Out of curiousity, is it possible to get the full asset path name?

For example, I generated the AssetMap and filtered for all Texture2D assets that start with `UI_`, however this is only the immediate name of the asset and I would like to get the full asset name path like in @radioegor146 's asset indices so that I can sort and organize all my exported assets.

e.g.:
- What I have: `UI_AvatarIcon_Side_Ambor`
- What I would like: `ART/UI/Atlas/AvatarSideIcon/UI_AvatarIcon_Side_Ambor`

**Comment by kvnxiao** [comment]
Got it, thanks for the explanation! Feel free to close this issue, or leave it open if you think this would be a nice enhancement in the far future to have.

**Comment by Razmoth** [comment]
Greetings,

This feature has been implemented in `v0.16.69`.
