### ISSUE TITLE
Some SpriteAtlasTexture Sprites not previewable/extractable

### ISSUE THREAD

**Issue by kvnxiao** [Razmoth/HoYoStudio#23]
For example from `C:\\Program Files\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\StreamingAssets\\AssetBundles\\blocks\\00\\14715084.blk`, the `Texture2D` asset: `SpriteAtlasTexture-ui_atlas_property_icons-256x128-fmt25`, the preview shows the following texture atlas:

![image](https://user-images.githubusercontent.com/14130413/183314204-834e9ed0-315b-41ee-81ac-cdf826decad1.png)

However, some of the individual `Sprite`s are not extractable:

![image](https://user-images.githubusercontent.com/14130413/183314283-c34a7285-b962-4365-b05c-65901909a36a.png)

In this case shown above, it seems that every sprite under the container `2047180531` is not extractable.

**Comment by Razmoth** [comment]
Greetings,

I've checked on some of the `Sprite`s, apparently those that don't work have their `PPtr` references set to null, so it's probably being handled differently (lookup by container or something).

will look more into this.
