### ISSUE TITLE
Can I export animation files?

### ISSUE THREAD

**Issue by byshiyi** [Razmoth/HoYoStudio#27]
Can I export animation files?
The current export will have a lot of error messages.

**Comment by Razmoth** [comment]
Greetings,

With `AssetStudio`, exporting animations is possible to some degree (legacy + generic animation atm), there's still no support to humanoid animations.

**Comment by byshiyi** [comment]
Can character animations be exported? I tested a lot of files, but there are hardly any animations

**Comment by Razmoth** [comment]
Greetings @byshiyi

Character animations can be partially exported, but since most of them are Humanoid (Genshin Impact) which are not supported by 'AssetStudio', so it won't play well.
