### ISSUE TITLE
Why sometimes I export Animator with Mesh and sometimes export without Mesh, is it because I have set something wrong?

### ISSUE THREAD

**Issue by byshiyi** [Razmoth/HoYoStudio#33]
Why sometimes I export Animator with Mesh and sometimes export without Mesh, is it because I have set something wrong?

**Comment by Razmoth** [comment]
Greetings,

That should be fine, some `Animator` do not have `m_Avatar` associated with them, and so with `AssetStudio`, those are going to export with empty model `FBX`.

Other tools are able to export those `Animator`s into a readable `YAML` format for `Unity Editor`.

**Comment by byshiyi** [comment]
![image](https://user-images.githubusercontent.com/10216522/186957281-ab91dfda-9fa7-4908-b892-3ff95dccb1e8.png)

**Comment by Razmoth** [comment]
Oh those are `YAML` outputs right ?

Might need to look for these mesh references in case anything's missing, other than that there's not much I could help with.
