### ISSUE TITLE
v0.16.65 broken changes cause assets missing.

### ISSUE THREAD

**Issue by peaceshi** [Razmoth/HoYoStudio#34]
GI game version: v3.0 official.
HoYoStudio version: v0.16.65.

assets_map.json exported by **v0.16.65** does not have `03933341.blk`.

And this version has too many duplicate assets, some GI game outdated version textures that haven't been used ever.

Everything works well in **v0.16.55**.

**03933341.blk has current v3.0 version texture.**

Others:

The assets_map.xml has them, and more invalid assets index. Textures are not in the blk file.

**Comment by Razmoth** [comment]
Greetings @peaceshi ,

This issue should be fixed with `v0.16.66`, let me know if it still persist.

**Comment by peaceshi** [comment]
Seems like everything works well with `v0.16.66`. Thanks and closed.
