### ISSUE TITLE
 export  "Tears of Themis"，to get audio res like mp3/wav

### ISSUE THREAD

**Issue by huwei19** [Razmoth/HoYoStudio#35]
hello，i want to exort  "Tears of Themis"，to get audio res like mp3/wav;
（1）build CABmap
（2）Build Assetmap
（3）get "assets_map.xml"
（4）"load folder"
but i get the wrong info:

![1unknown](https://user-images.githubusercontent.com/20811240/187331974-ca030a2e-ce6a-4a63-aa4c-135b15fa50b8.png)
![2unknown](https://user-images.githubusercontent.com/20811240/187331979-9b806aa5-33bd-41ee-9a6e-f4626a0e75ee.png)
![3unknown](https://user-images.githubusercontent.com/20811240/187331981-abfd4b8e-c086-49ce-be4b-eac50e8c34c3.png)

**Comment by Razmoth** [comment]
Greetings @huwei19,

Audio files in `Tears of Themis` as `WWise PCK` files as it seems, `AssetStudio` is not able to load those.

**Comment by huwei19** [comment]
收到邮件咯。
